"""empty message

Revision ID: 6d24af4744c0
Revises: b39e7cc61304
Create Date: 2021-10-21 06:55:24.615995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d24af4744c0'
down_revision = 'b39e7cc61304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ordinal_number', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ordinal_number')
    # ### end Alembic commands ###
